chore: 🔧 use Foundry's API to publish the new versions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -89,12 +89,39 @@ jobs:
           artifacts: './${{ steps.name.outputs.prop }}-fvtt_v${{ steps.version.outputs.prop }}.zip, ./dist/${{ env.TYPE }}.json'
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      # Publishes the release to the FoundryVTT's package repository.
+      - name: Get Compatibility
+        run: |
+          echo 'COMPATIBILITY<<EOF' >> $GITHUB_ENV
+          cat dist/${{ env.TYPE }}.json | jq .compatibility >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+
       - name: 🚩 Publish Module to FoundryVTT Website
-        uses: Varriount/fvtt-autopublish@v2.0.2
-        with:
-          username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
-          password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
-          module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_NAME }}
-          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/${{ env.TYPE }}.json
-          manifest-file: dist/${{ env.TYPE }}.json
+        run: |
+          HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X POST 'https://foundryvtt.com/_api/packages/release_version/' \
+          --header 'Authorization: ${{ secrets.PACKAGE_TOKEN }}' \
+          --header 'Content-Type: application/json' \
+          --data '{
+              "id": "${{ steps.name.outputs.prop }}",
+              "dry-run": ${{github.event.release.prerelease}},
+              "release": {
+                  "version": "${{ github.event.release.tag_name }}",
+                  "manifest": "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/${{ env.TYPE }}.json",
+                  "notes": "https://github.com/${{github.repository}}/releases/tag/${{github.event.release.tag_name}}",
+                  "compatibility": ${{ env.COMPATIBILITY }}
+              }
+          }')
+          
+          # extract the body
+          HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+          
+          # extract the status
+          HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+          
+          # print the body
+          echo "$HTTP_BODY"
+          
+          # example using the status
+          if [ ! $HTTP_STATUS -eq 200  ]; then
+            echo "Error [HTTP status: $HTTP_STATUS]"
+            exit 1
+          fi
